# Generated by Django 5.0.6 on 2024-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
